doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: 'mysql://%env(MYSQL_USERNAME)%:%env(MYSQL_PASSWORD)%@%env(MYSQL_HOST)%:%env(MYSQL_PORT)%/%env(MYSQL_DATABASE_NAME)%'
                server_version: '%env(MYSQL_SERVER_VERSION)%'
            migrations:
                url: 'mysql://%env(MYSQL_MIGRATIONS_USERNAME)%:%env(MYSQL_MIGRATIONS_PASSWORD)%@%env(MYSQL_HOST)%:%env(MYSQL_PORT)%/%env(MYSQL_DATABASE_NAME)%'
                server_version: '%env(MYSQL_SERVER_VERSION)%'

        types:
            ######################  DEVICES  ######################
            vending_machine_id: VM\Context\Devices\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\VendingMachineIdType
            currency_id: VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\CurrencyIdType
            currency_value: VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\CurrencyValueType
            currency_kind: VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\CurrencyKindType
            cash_id: VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\CashIdType
            cash_item_id: VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\CashItemIdType
            cash_amount: VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\AmountType
            cash_vending_machine_id: VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\VendingMachineIdType

    orm:
        entity_managers:
            vm:
                connection: default
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Devices:
                        type: xml
                        dir: '%kernel.project_dir%/src/Context/Devices/Infrastructure/Write/Persistence/Doctrine/MySQL/Mapping'
                        prefix: 'VM\Context\Devices\Domain\Write'
                        is_bundle: false
                    Payment:
                        type: xml
                        dir: '%kernel.project_dir%/src/Context/Payment/Infrastructure/Write/Persistence/Doctrine/MySQL/Mapping'
                        prefix: 'VM\Context\Payment\Domain\Write'
                        is_bundle: false
