services:
  nginx-server:
    image: nginx:1.24
    container_name: vending_machine_nginx_server
    depends_on:
      - php-fpm
    links:
      - php-fpm
    volumes:
      - ./:/var/www/vending_machine:delegated
      - ./resources/docker/local/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8800:80"

  php-fpm:
    build: resources/docker/local/php-fpm
    container_name: vending_machine_php_fpm
    working_dir: /var/www/vending_machine
    volumes:
      - ./:/var/www/vending_machine:delegated
      - /var/www/vending_machine/var/
      - ./resources/docker/local/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  mysql:
      container_name: vending_machine_mysql
      image: mysql:8.0.32
      extends:
          file: resources/docker/local/mysql/volume_mappings.yml
          service: vending_machine_mysql
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: vending_machine
          MYSQL_USER: vending_machine_user
          MYSQL_PASSWORD: vending_machine_password
      ports:
          - '13336:3306'
