services:
    _defaults:
        public: true

    test.VM\Context\Devices\Domain\Write\Repository\VendingMachineRepository: '@VM\Context\Devices\Infrastructure\Write\Persistence\Doctrine\MySQL\Repository\DoctrineVendingMachineRepository'
    test.VM\Context\Payment\Domain\Write\Repository\CurrencyRepository: '@VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Repository\DoctrineCurrencyRepository'
    test.VM\Context\Payment\Domain\Write\Repository\CashRepository: '@VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Repository\DoctrineCashRepository'
    test.VM\Context\Payment\Domain\Write\Repository\FundRepository: '@VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Repository\DoctrineFundRepository'
