services:
    _defaults:
        public: true

    test.VM\Context\Devices\Domain\Write\Repository\VendingMachineRepository: '@VM\Context\Devices\Infrastructure\Write\Persistence\Doctrine\MySQL\Repository\DoctrineVendingMachineRepository'
    test.VM\Context\Payment\Domain\Write\Repository\CurrencyRepository: '@VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Repository\DoctrineCurrencyRepository'
    test.VM\Context\Payment\Domain\Write\Repository\CashRepository: '@VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Repository\DoctrineCashRepository'
    test.VM\Context\Payment\Domain\Write\Repository\FundRepository: '@VM\Context\Payment\Infrastructure\Write\Persistence\Doctrine\MySQL\Repository\DoctrineFundRepository'
    test.VM\Context\Product\Domain\Write\Repository\ProductRepository: '@VM\Context\Product\Infrastructure\Write\Persistence\Doctrine\MySQL\Repository\DoctrineProductRepository'
    test.VM\Context\Product\Domain\Write\Repository\StockRepository: '@VM\Context\Product\Infrastructure\Write\Persistence\Doctrine\MySQL\Repository\DoctrineStockRepository'

    VM\Tests\Infrastructure\Acceptance\Behat\Context\ApiContext:
        arguments:
            - '@kernel'
    VM\Tests\Infrastructure\Acceptance\Behat\Context\PaymentContext:
        arguments:
            - '@kernel'

